#ifndef RENDERER_DEFINE_H
#define RENDERER_DEFINE_H

namespace KI
{
namespace Rednerer
{
#define SCENE_DATA_LOCATION		5
#define LIGHT_DATA_LOCATION		6
#define MODEL_DATA_LOCATION		7
#define MATERIAL_DATA_LOCATION	8
}
}
#endif RENDERER_DEFINE_H