#ifndef RENDER_TYPE_H
#define RENDER_TYPE_H
namespace KI
{
namespace Renderer
{

enum VERTEX_ATTRIB
{
	VERTEX_ATTRIB_POSITION			= 0x00,
	VERTEX_ATTRIB_NORMAL			= 0x01,
	VERTEX_ATTRIB_COLOR				= 0x02,
	VERTEX_ATTRIB_TEXCOORD			= 0x03,
	VERTEX_ATTRIB_INSTANCE_MATRIX0	= 0x04,	// row0
	VERTEX_ATTRIB_INSTANCE_MATRIX1	= 0x05,	// row1
	VERTEX_ATTRIB_INSTANCE_MATRIX2	= 0x06,	// row2
	VERTEX_ATTRIB_INSTANCE_MATRIX3	= 0x07,	// row3
	VERTEX_ATTRIB_NUM				= 0xFF
};

enum VERTEX_LAYOUT
{
	VERTEX_LAYOUT_NONE				= 0x00,
	VERTEX_LAYOUT_POSITION			= 0x01,
	VERTEX_LAYOUT_NORMAL			= 0x02,
	VERTEX_LAYOUT_COLOR				= 0x04,
	VERTEX_LAYOUT_TEXCOORD			= 0x08,
	VERTEX_LAYOUT_INSTANCE_MATRIX0	= 0x10,	// row0
	VERTEX_LAYOUT_INSTANCE_MATRIX1	= 0x20,	// row1
	VERTEX_LAYOUT_INSTANCE_MATRIX2	= 0x40,	// row2
	VERTEX_LAYOUT_INSTANCE_MATRIX3	= 0x80,	// row3
	VERTEX_LAYOUT_NUM				= 0xFF
};

enum SHADERPASS_TYPE
{
	SHADERPASS_TYPE_DEFAULT,
	SHADERPASS_TYPE_GENERAL,
	SHADERPASS_TYPE_OUTPUT_BUFFER,
	SHADERPASS_TYPE_PFX
};


enum PICK_TYPE
{
	
	PICK_TYPE_POINT		= 0x01,
	PICK_TYPE_LINE		= 0x02,
	PICK_TYPE_FACE		= 0x04,
	PICK_TYPE_OBJECT	= 0x08
};

enum TOPOLOGY_TYPE
{
	TOPOLOGY_TYPE_POINT	= 0x01,
	TOPOLOGY_TYPE_LINE	= 0x02,
	TOPOLOGY_TYPE_FACE	= 0x04,
};

enum SHADING_TYPE
{
	SHADING_TYPE_ADS,
	SHADING_TYPE_BASIC,
	SHADING_TYPE_VERTEX,
};

enum SHADER_INCLUDE
{
	SHADER_INCLUDE_COMMON,
	SHADER_INCLUDE_DEFINE,
};

enum SHADER_VBO
{
	SHADER_VBO_DEFAULT
};
}
}

#endif RENDER_TYPE_H
