#ifndef RENDER_TYPE_H
#define RENDER_TYPE_H
namespace KI
{
namespace Renderer
{

enum VERTEX_ATTRIB
{
	VERTEX_ATTRIB_POSITION	= 0x00,
	VERTEX_ATTRIB_NORMAL	= 0x01,
	VERTEX_ATTRIB_COLOR		= 0x02,
	VERTEX_ATTRIB_TEXCOORD	= 0x03,
	VERTEX_ATTRIB_NUM		= 0xFF
};

enum VERTEX_LAYOUT
{
	VERTEX_LAYOUT_NONE		= 0x00,
	VERTEX_LAYOUT_POSITION	= 0x01,
	VERTEX_LAYOUT_NORMAL	= 0x02,
	VERTEX_LAYOUT_COLOR		= 0x04,
	VERTEX_LAYOUT_TEXCOORD	= 0x08,
	VERTEX_LAYOUT_NUM		= 0xFF
};

enum MATERIAL_TYPE
{
	MATERIAL_TYPE_DEFAULT,
	MATERIAL_TYPE_POINTMATERIAL,
	MATERIAL_TYPE_LINEMATERIAL,
	MATERIAL_TYPE_OUTPUT_BUFFER
};
}
}

#endif RENDER_TYPE_H
