#ifndef KI_GFX_TYPES_H
#define KI_GFX_TYPES_H

namespace KI
{
namespace Gfx
{
enum STATE_TYPE
{
	STATE_TYPE_POINT,
	STATE_TYPE_LINE,
	STATE_TYPE_DEPTH,
	STATE_TYPE_CULL,
	STATE_TYPE_POLYGON,
	STATE_TYPE_BLEND
};

enum VERTEX_BUFFER_TYPE
{
	VERTEX_BUFFER_TYPE_NONE,
	VERTEX_BUFFER_TYPE_DEFAULT
};

enum SHADER_TYPE
{
	SHADER_TYPE_DEFAULT		= 1,
	SHADER_TYPE_OUTPUT		= 2,
	SHADER_TYPE_COMPOSIT	= 3,
	SHADER_TYPE_GRAYSCALE	= 4,
	SHADER_TYPE_SSLIC		= 5,
	SHADER_TYPE_POSTPROCESS = 6,
	SHADER_TYPE_NORMALVISUALIZE = 7,
	SHADER_TYPE_BEZIERLINE	= 8,
	SHADER_TYPE_TANGENTVISUALIZE = 9,
	SHADER_TYPE_PICK		= 10,
	SHADER_TYPE_MESH_PARAMETERIZATION = 11,
};

enum FRAMEBUFFER_ATTACHMENT
{
	FRAMEBUFFER_COLOR_ATTACHMENT0 = 0,
	FRAMEBUFFER_COLOR_ATTACHMENT1 = 1,
	FRAMEBUFFER_COLOR_ATTACHMENT2 = 2,
	FRAMEBUFFER_COLOR_ATTACHMENT3 = 3,
	FRAMEBUFFER_DEPTH_ATTATCHMENT = 4,
	FRAMEBUFFER_STENCIL_ATTATCHMENT = 5,
};
}
}

#endif KI_GFX_TYPES_H
