#ifndef KI_GFX_TYPES_H
#define KI_GFX_TYPES_H

namespace KI
{
namespace Gfx
{
enum STATE_TYPE
{
	STATE_TYPE_POINT,
	STATE_TYPE_LINE,
	STATE_TYPE_DEPTH,
	STATE_TYPE_CULL,
	STATE_TYPE_POLYGON,
};

enum VERTEX_BUFFER_TYPE
{
	VERTEX_BUFFER_TYPE_DEFAULT
};

enum SHADER_TYPE
{
	SHADER_TYPE_DEFAULT		= 1,
	SHADER_TYPE_OUTPUT		= 2,
	SHADER_TYPE_COMPOSIT	= 3,
	SHADER_TYPE_GRAYSCALE	= 4,
	SHADER_TYPE_SSLIC		= 5,
	SHADER_TYPE_POSTPROCESS = 6,
	SHADER_TYPE_NORMALVISUALIZE = 7,
	SHADER_TYPE_BEZIERLINE	= 8,
	SHADER_TYPE_PICK		= 9
};

enum RENDER_TEXTURE_TYPE
{
	RENDER_COLOR_TEXTURE,
	RENDER_DEPTH_TEXTURE,
	RENDER_STENCIL_TEXTURE,
};
}
}

#endif KI_GFX_TYPES_H
